pharmaverse/logrx

R/axecute.R
man/axecute.Rd
tests/testthat/test-axecute.R

Session quits with status 1 on error during non-interactive runs

Tweak axecute return

---

.github/PULL_REQUEST_TEMPLATE/release.md
DESCRIPTION
NEWS.md
R/utils-approved.R
inst/WORDLIST
man/build_approved.Rd
vignettes/articles/adsl_demo.Rmd
vignettes/articles/tables.Rmd

Updates pertaining to Release QC of Release v0.1.0

spelling, DESCRIPTION, and PR template updates

---

README.Rmd
README.md

update to have gif included from hosted location

---

DESCRIPTION
README.Rmd
README.md
inst/rstudio/addins.dcf

100 95 readme description

---

.github/pull_request_template.md
DESCRIPTION
NEWS.md
R/interact.R
R/zzz.R
tests/testthat/ref/run_file_test.R
tests/testthat/ref/run_file_test_current_env.R
tests/testthat/ref/run_file_test_parent_env.R
tests/testthat/test-interact.R

Closes #104 
logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well …

Fix 104 Code Execution Environment

---

DESCRIPTION
NEWS.md
R/interact.R
man/set_log_name_path.Rd

Closes #116 CRAN documentation updates

---

NEWS.md
vignettes/options.Rmd

Closes #124 
logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well …

Closes #124

---

NEWS.md
vignettes/approved.Rmd

Closes #105

---

.github/workflows/test-coverage.yaml

Closes #132 
logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well …

Closes #132

---

vignettes/approved.Rmd

Closes #123
logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well …

Closes #123

---

DESCRIPTION
README.md

update docs to get gif working and all checks good

---

vignettes/logrx.Rmd

correct link to execution vignette

---

.github/workflows/check-standard.yaml
DESCRIPTION
NEWS.md
_pkgdown.yml

Closes #179 website refresh

---

.github/pull_request_template.md
.github/workflows/version-bump.yaml
DESCRIPTION
NEWS.md
README.Rmd
_pkgdown.yml

Closes #209 new version who this?

---

tests/testthat/test-get.R
tests/testthat/test-writer.R

For #231. Not marking as closed; as suggested, I think there's more to be done here, but this will get the test back in CRAN-ready shape ASAP.
Of course, if you'd rather not be bothered investing further in the test, you can just mark the issue closed anyway :)

update lintr output

---

R/get.R
tests/testthat/test-get.R

Closes #238

---

.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

issue with rsetupv1 as well.  updated to v2

Fix 248 using v2 now

---

R/axecute.R
R/log.R
R/writer.R
tests/testthat/test-axecute.R
tests/testthat/test-get.R
tests/testthat/test-log.R
tests/testthat/test-writer.R

Closes #180 by fixing styling using styler

---

.github/workflows/test-coverage.yaml
README.Rmd
README.md

Closes #256 new workflow for test coverage

---

.github/workflows/R-CMD-check.yaml
README.Rmd
README.md
inst/WORDLIST

remove old test badge; added pharmaverse badge

---

vignettes/generate-lockfile.Rmd

Set eval to false to fix 263
